kind: pipeline
name: default
steps:
  - name: test
    image: node:8-alpine
    pull: true
    commands:
      - yarn install
      - yarn run build
      - yarn run test

  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email: dean@ethicaljobs.com.au
    when:
      status: success
      event: tag

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments