pipeline:

  test:
    image: node:8-alpine
    pull: true
    commands:
      - yarn install
      - yarn run build
      - yarn run test

  publish:
    image: plugins/npm
#    secrets: [ npm_username, npm_password ]
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email: dean@ethicaljobs.com.au
    when:
      status: success
      event: tag

#  notify-slack:
#    image: plugins/slack
#    webhook: https://hooks.slack.com/services/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
#    channel: deployments
